### ISSUE TITLE
Crash on init

### ISSUE THREAD

**Issue by DennisDreissen** [PhamBaTho/BTNavigationDropdownMenu#13]
I can't get the drop down menu to work, it keeps crashing as soon as it starts loading. It crashes at the point where it creates the frame in the "init" function. I am using Xcode 6.4 with iOS 8.

Here's my code:

    import UIKit
    import CVCalendar
    import BTNavigationDropdownMenu

    class RosterViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate {
    
    @IBOutlet weak var menuButton:UIBarButtonItem!
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var calendarView: CVCalendarView!
    @IBOutlet weak var menuView: CVCalendarMenuView!
    
    var menuViewNav: BTNavigationDropdownMenu!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView.delegate = self
        tableView.dataSource = self
        tableView.tableFooterView = UIView()
        
        let items = ["Most Popular", "Latest", "Trending", "Nearest", "Top Picks"]
        menuViewNav = BTNavigationDropdownMenu(title: "Hey", items: items)
        menuViewNav.didSelectItemAtIndexHandler = {(indexPath: Int) -> () in
            print("Did select item at index: \(indexPath)")
        }
        self.navigationItem.titleView = menuViewNav
        
        if self.revealViewController() != nil {
            menuButton.target = self.revealViewController()
            menuButton.action = "revealToggle:"
            self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
        }
    }

**Comment by DennisDreissen** [comment]
I fixed it by setting the navigationController manually. I'm now sending the navigationController together with the title and the items.

    BTNavigationDropdownMenu(title: "Hey", items: items, nav: navigationController!)

Not sure if this is the proper way to do it, but at least it works.

**Comment by Magrider** [comment]
Same issue, crashing on // Set frame
        let frame = CGRectMake(0, 0, titleSize.width + (self.configuration.arrowPadding + self.configuration.arrowImage.size.width)*2, (self.navigationController?.navigationBar.frame.height)!)
  
show  thread 1 exc_bad_instruction (code=exc_i386_invop subcode=0x0)

The navigationController is nil.

**Comment by PhamBaTho** [comment]
Hi, please check [this commit](https://github.com/PhamBaTho/BTNavigationDropdownMenu/commit/daa1304751b3518a3f98129d3df04151f0f62fb4). I fixed bug relating to the availability of navigation controller. I also updated to CocoaPods for this fix (version 0.1.8).

**Comment by croossin** [comment]
I am as well getting the same error that @Magrider is getting.  I have the latest commit and it still throws that error.  However your demo project works.  Can this drop down be implemented on a standard view?

**Comment by stevesarkisian-tribpub** [comment]
I'm getting same exact issue, The navigationController is nil.  Using CocoaPods version 0.1.8.

**Comment by whitefoxy** [comment]
The same error

**Comment by liberty4me** [comment]
The top viewcontroller in my app is a UITabBarController instead of UINavigationController, so I think it should be able to set by programmer.

**Comment by PhamBaTho** [comment]
@liberty4me 👍
